services:
  - type: web
    name: xray-proxy-ping-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: PROXY_PING_HOST
        value: 0.0.0.0
      - key: PROXY_PING_PORT
        value: 10000
